[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'sorah/unite-ghq'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
on_map = 'go'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = 'typescript'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

